# Write your MySQL query statement below
-- SELECT ID, MOVIE, DESCRIPTION, RATING
-- FROM CINEMA
-- WHERE DESCRIPTION != 'boring' AND ID % 2 != 0
-- GROUP BY ID
-- ORDER BY RATING DESC;

SELECT *
FROM CINEMA
WHERE DESCRIPTION != 'boring' AND ID % 2 != 0
ORDER BY RATING DESC;