# Write your MySQL query statement below
SELECT ROUND(COUNT(A.PLAYER_ID) / (
    SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY
), 2) AS FRACTION
FROM ACTIVITY A
WHERE (A.PLAYER_ID, DATE_SUB(A.EVENT_DATE, INTERVAL 1 DAY)) IN (
    SELECT PLAYER_ID, MIN(EVENT_DATE)
    FROM ACTIVITY
    GROUP BY PLAYER_ID
)

;
