# Write your MySQL query statement below
SELECT S.NAME
FROM SALESPERSON S
WHERE S.NAME NOT IN (
    SELECT S.NAME
    FROM SALESPERSON S
    LEFT JOIN ORDERS O
    ON S.SALES_ID = O.SALES_ID
    LEFT JOIN COMPANY C
    ON O.COM_ID = C.COM_ID
    WHERE C.NAME = 'RED'
);

