/* Write your PL/SQL query statement below */
SELECT P.PRODUCT_NAME, SUM(O.UNIT) AS UNIT
FROM PRODUCTS P
JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(O.ORDER_DATE, 'YYYY-MM') = '2020-02'
GROUP BY PRODUCT_NAME
HAVING SUM(O.UNIT) > 99