# Write your MySQL query statement below
SELECT D.NAME AS Department, E.NAME AS Employee, E.SALARY AS Salary
FROM EMPLOYEE E 
JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.ID
WHERE (
    SELECT COUNT(DISTINCT SALARY) FROM EMPLOYEE E2
    WHERE E2.DEPARTMENTID = E.DEPARTMENTID AND 
    E2.SALARY >= E.SALARY
) <= 3
ORDER BY 1, 3 DESC