# Write your MySQL query statement below
SELECT A.MACHINE_ID AS "machine_id", 
ROUND(AVG(B.TIMESTAMP - A.TIMESTAMP), 3) AS "processing_time"
FROM ACTIVITY A, ACTIVITY B
WHERE A.MACHINE_ID = B.MACHINE_ID 
AND A.PROCESS_ID = B.PROCESS_ID
AND A.ACTIVITY_TYPE = 'start' 
AND B.ACTIVITY_TYPE = 'end'
GROUP BY MACHINE_ID;

