# Write your MySQL query statement below
(SELECT NAME AS RESULTS 
FROM MOVIERATING 
JOIN USERS USING(USER_ID)
GROUP BY NAME
ORDER BY COUNT(*) DESC, NAME
LIMIT 1)

UNION ALL 

(SELECT TITLE AS RESULTS 
FROM MOVIERATING 
JOIN MOVIES USING(MOVIE_ID)
-- WHERE TO_CHAR(CREATED_AT, 'MM-YYYY') = '02-2020'
WHERE EXTRACT(YEAR_MONTH FROM CREATED_AT) = 202002
GROUP BY TITLE
ORDER BY AVG(RATING) DESC , TITLE
LIMIT 1) ;