# Write your MySQL query statement below
SELECT ID, SUM(NUM) AS NUM
FROM (
SELECT REQUESTER_ID AS ID, COUNT(REQUESTER_ID) AS NUM
FROM RequestAccepted 
GROUP BY REQUESTER_ID

UNION ALL

SELECT ACCEPTER_ID AS ID, COUNT(ACCEPTER_ID) AS NUM
FROM RequestAccepted 
GROUP BY ACCEPTER_ID ) AS UNION_TABLE

GROUP BY ID
ORDER BY NUM DESC
LIMIT 1